create schema blog;

-- auto-generated definition
create table blog.t_article
(
    id         bigint not null
        constraint t_article_pk
            primary key,
    title      varchar(255),
    descript   varchar(255),
    body       text,
    gmt_create timestamp,
    gmt_update timestamp,
    label      varchar(50)
);

alter table blog.t_article
    owner to postgres;

-- auto-generated definition
create table blog.t_record
(
    id         bigint generated by default as identity
        constraint t_record_pk
            primary key,
    ip         varchar(100),
    api_url    varchar(200),
    gmt_create timestamp,
    time       numeric(10, 3)
);

alter table blog.t_record
    owner to postgres;


-- auto-generated definition
create table blog.t_user
(
    id         bigint not null
        constraint t_user_pk
            primary key,
    name       varchar(20)
        constraint t_user_pk_2
            unique,
    password   varchar(100),
    nickname   varchar(100),
    gmt_create timestamp,
    img_url    varchar(500),
    github     varchar(500),
    email      varchar(100),
    record     varchar(500),
    title      varchar(500),
    title2     varchar(500),
    background json
);

alter table blog.t_user
    owner to postgres;
insert into blog.t_user (id, name, password, nickname, gmt_create, img_url, github, email, record, title, title2,
                         background)
values (1, 'admin', '$2a$10$kE5p6Q6mDvXOBU3jOLgu9u8cKRXyifbiE8M5DgmIFToVYB0.EhO22', '1', '2024-08-07 16:25:21.000000',
        'https://chatgpt.com/c/6fca2a1e-ef1d-4851-a8a0-ff8378f4d973', 'hello.com2', 'hello.com', '523523423423', '7765',
        '5534', '[
    "https://pic1.zhimg.com/80/v2-a60039109162ef97e005e63035dc3264_720w.webp"
  ]');
