server:
  port: 8088
  servlet:
    context-path: /blog

spring:
  datasource:
    username: **************
    password: **************
    url: jdbc:mysql://**************:**************/myBlog?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #自动峰驼
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:com/li/blog/mapper/xml/*.xml

logging:
  config: classpath:logback-spring.xml

#jwt拦截url
permission-config:
  perms:
    #    swaggwr放行
    - key: /v2/api-docs
      value:  anon
    - key: /webjars/**
      value: anon
    - key: /swagger-resources/**
      value: anon
    - key: /swagger-ui.html
      value: anon
    - key: /doc.html
      value: anon

    - key: /**
      value: jwt