version: "3"
services:

  nblog-redis:
    image: redis:5.0.9-alpine
    container_name: redis
    restart: always
    volumes:
      - ${DATA_DIRECTORY}/data/redis/data:/data
    networks:
      nblog-network:
        ipv4_address: ${REDIS_HOST:-172.20.0.2}
    ports:
      - ${REDIS_PORT:-6379}:6379
    # --requirepass 后面为redis访问密码
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

  nblog-mysql:
    #仅支持amd64
    image: jiuxiajingfan/nblog-mysql:0.1
    container_name: nblog-mysql
    restart: always
    volumes:
      - ${DATA_DIRECTORY}/data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # mysql数据库root账号的密码
      - TZ=Asia/Shanghai
    ports:
      - ${MYSQL_PORT:-5683}:3306
    networks:
      nblog-network:
        ipv4_address: ${MYSQL_HOST:-172.20.0.3}

  nblog-frontend:
    #仅支持amd64
    image: jiuxiajingfan/nblog-vue:0.1
    container_name: nblog-vue
    restart: always
    ports:
      - "8092:8092"
      - "4437:443"
    networks:
      nblog-network:
        ipv4_address: 172.20.0.6

  nblog:
    image: jiuxiajingfan/nblog:0.1
    container_name: nblog
    restart: always
    depends_on:
      - nblog-redis
      - nblog-mysql
    environment:
      - DB_USER=root
      - DB_HOST=${MYSQL_HOST:-172.20.0.3}
      - DB_PORT=${MYSQL_PORT:-5683}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-172.20.0.2}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Shanghai
    ports:
      - 3641:3641
    networks:
      nblog-network:
        ipv4_address: 172.20.0.4

networks:
  nblog-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16